ingress:
  enabled: true
  host: demo.apps.dataease.com
  annotations: {}
    ## example for ingress annotions.
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"      
  https:
    enabled: false
    secretName: ""

common:
  imagePrefix: "registry.qingteng.cn/ms-infra/dataease/"
  imagePullPolicy: IfNotPresent
  storageClass: ""
  imagePullSecrets: "qt-registry"

  mysql: 
    host: mysql
    port: 3306
    username: root
    password: Password123@mysql
  mongobi: 
    host: mongobi
  dataease:
    host: dataease
    initpassword: DataEase123456
    logintimeout: 480
    nodeport_host: dataease-http
    nodeport_port: 30081

DataEase:
  enabled: true
  engine_mode: simple
  image: dataease
  imageTag: "v1.18.10"
  replicas: 1
  resourceLimits:
    cpu: 4
    memory: 8G
  properties: |-
    spring.datasource.url=jdbc:mysql://{{.Values.common.mysql.host}}:{{.Values.common.mysql.port}}/dataease?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username={{.Values.common.mysql.username}}
    spring.datasource.password={{.Values.common.mysql.password}}
    dataease.init_password={{.Values.common.dataease.initpassword}}
    dataease.login_timeout={{.Values.common.dataease.logintimeout}}
    logger.level=INFO
    engine_mode={{.Values.DataEase.engine_mode}}

mysql:
  enabled: true
  image: mysql
  imageTag: "5.7.41"
  resourceLimits:
    cpu: 4
    memory: 8G
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 20Gi

mongobi:
  enabled: true
  image: mongobi
  imageTag: "v2.14.9"
  resourceLimits:
    cpu: 4
    memory: 8G

doris_fe:
  enable: false
  host: doris-fe
  imagePrefix: "uhub.service.ucloud.cn/dataease/"
  image: doris-fe
  imageTag: "v1.1.3"
  resourceLimits:
    cpu: 4
    memory: 8G
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 10Gi

doris_be:
  enable: false
  host: doris-be
  imagePrefix: "uhub.service.ucloud.cn/dataease/"
  image: doris-be
  imageTag: "v1.1.3"
  resourceLimits:
    cpu: 4
    memory: 8G
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 20Gi

kettle:
  image: kettle
  imageTag: "v8.3-0318"
  java_options: "-Xms1024m -Xmx4096m -XX:MaxPermSize=256m -Dfile.encoding=utf-8"
  host: kettle
  replicas: 1
  resourceLimits:
    cpu: 4
    memory: 8G
  persistence:
    accessModes: ReadWriteMany
    size: 10Gi  

logPersistence:
  enabled: true
  accessModes: ReadWriteOnce
  size: 10Gi

dataPersistence:
  enabled: true
  accessModes: ReadWriteOnce
  size: 10Gi
