{{if and (eq .Values.DataEase.engine_mode "cluster") (.Values.doris_be.enable)}}
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: {{.Values.doris_be.host}}
  labels:
    app: {{.Values.doris_be.host}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.doris_be.host}}
  template:
    metadata:
      labels:
        app: {{.Values.doris_be.host}}
    spec:
      #nodeName: master-1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{.Values.doris_be.host}}
          env:
            - name: BE_IPADDRESS
              valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
          image: {{.Values.doris_be.imagePrefix}}{{.Values.doris_be.image}}:{{.Values.doris_be.imageTag}}
          command: [ "/bin/bash", "-ce", "/opt/doris/bin/start_be.sh --daemon;tail -f /dev/null" ]
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8040
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3            
          ports:
            - containerPort: 9060
              protocol: TCP
            - containerPort: 9070
              protocol: TCP
            - containerPort: 8040
              protocol: TCP
            - containerPort: 9050
              protocol: TCP
            - containerPort: 8060
              protocol: TCP
          resources:
            limits:
              cpu: {{.Values.doris_be.resourceLimits.cpu}}
              memory: {{.Values.doris_be.resourceLimits.memory}}
            requests:
              cpu: 200m
              memory: 1G
          volumeMounts:
            - mountPath: /opt/doris/storage
              name: opt-be-storage
            - mountPath: /opt/doris/conf/be.conf
              name: opt-doris-be-config
              subPath: be.conf
      volumes:
      - name: opt-be-storage
        persistentVolumeClaim:
          claimName: doris-be-pvc
      - name: opt-doris-be-config
        configMap:
          name: be-config
{{end}}
