{{ if .Values.dataPersistence.enabled}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataease-plugins-thirdpart-pvc
spec:
  accessModes:
    - {{.Values.dataPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.dataPersistence.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}  
