{{ if .Values.logPersistence.enabled}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataease-logs-pvc
spec:
  accessModes:
    - {{.Values.logPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.logPersistence.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}  
