{{if and (eq .Values.DataEase.engine_mode "cluster") (.Values.doris_fe.enable)}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doris-fe-pvc
spec:
  accessModes:
    - {{.Values.doris_fe.persistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.doris_fe.persistence.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}
---
{{if and (eq .Values.DataEase.engine_mode "cluster") (.Values.doris_be.enable)}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doris-be-pvc
spec:
  accessModes:
    - {{.Values.doris_be.persistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.doris_be.persistence.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}
